### ISSUE TITLE
Ben Haircut

### ISSUE THREAD

**Issue by charmalt** [charmalt/final-project-pop#5]
Acceptance Criteria:
- Hair is shorter
- Cost below 20 pounds 
- Minimal Small Talk 
- Minimal Hair on Tshirt

**Comment by benfurber** [comment]
* Hair is definitely shorter. 
* Cost was £16 (inc. tip)
* Small talk was minimised by giving boring/short answers to early attempts at conversation by stylist
* No noticeable hair on tshirt - some remained on face but was easily removed by toilet roll

@JohnNewman1 @charmalt @georgesykes86 @nixlim - Please provide feedback on outcome.
